from __future__ import annotations

DEFAULT_MAX_ROUNDS = 7
DEFAULT_RESOLUTION_THRESHOLD = 0.80
DEFAULT_ESCALATION_THRESHOLD = 0.85
DEFAULT_LOW_CHANGE_DELTA_THRESHOLD = 0.02
DEFAULT_LOW_CHANGE_ROUND_LIMIT = 5
DEFAULT_CONFLICT_PATTERN_REPEAT_LIMIT = 5

# DEFAULT_PRIMARY_MODEL = "hf.co/unsloth/Mistral-Small-3.2-24B-Instruct-2506-GGUF:Q4_0"
DEFAULT_PRIMARY_MODEL = "hf.co/unsloth/Llama-3.2-3B-Instruct-GGUF:BF16"
DEFAULT_EMBEDDING_MODEL = "nomic-embed-text"

DEFAULT_TRACE_DIR = "artifacts"
DEFAULT_TRACE_FILE_NAME = "trace.jsonl"
DEFAULT_FINAL_OUTPUT_FILE_NAME = "final_output.json"
DEFAULT_SUMMARY_FILE_NAME = "summary.md"

DEFAULT_ROUND_STATUS = "active"
DEFAULT_SCENARIO_STATUS = "active"

DEFAULT_MAX_OBJECTIVES = 5
DEFAULT_MAX_RISKS = 5
DEFAULT_MAX_ACTION_TARGETS = 3