from __future__ import annotations


def _rel(
    source: str,
    target: str,
    *,
    association: str,
    trust: float,
    alignment: float,
    conflict: float,
    dependency: float,
    influence: float,
    reliability: float,
    history: str,
    tags: list[str] | None = None,
) -> dict:
    return {
        "source_actor_id": source,
        "target_actor_id": target,
        "trust": trust,
        "alignment": alignment,
        "conflict_level": conflict,
        "dependency": dependency,
        "influence": influence,
        "perceived_reliability": reliability,
        "history_summary": history,
        "metadata": {
            "association": association,
            "tags": tags or [],
        },
    }


def build_us_iran_regional_crisis_input() -> dict:
    actors = [
        {
            "actor_id": "actor_us",
            "name": "United States",
            "role_label": "state_power",
            "role_description": (
                "Principal military actor seeking to preserve deterrence, protect deployed forces, "
                "keep regional partners aligned, and avoid strategic humiliation."
            ),
            "base_objectives": [
                "restore deterrence against Iran",
                "protect US personnel, bases, and shipping lanes",
                "preserve coalition cohesion with Israel and Gulf partners",
                "retain a diplomatic off-ramp on favorable terms",
            ],
            "base_priorities": {
                "deterrence": 0.95,
                "force_protection": 0.92,
                "coalition_management": 0.78,
                "deescalation": 0.42,
            },
            "constraints": [
                "domestic political pressure not to appear weak",
                "allied expectations",
                "risk of wider regional war",
                "economic shock from sustained maritime disruption",
            ],
            "capabilities": [
                "propose",
                "request",
                "challenge",
                "support",
                "resist",
                "escalate",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "major additional casualties at US bases",
                "sustained Hormuz closure",
                "loss of coalition credibility",
            ],
            "interaction_style": "assertive",
            "metadata": {
                "bloc": "western_security",
                "association_map": {
                    "actor_israel": "aligned",
                    "actor_iran": "adversarial",
                    "actor_saudi": "security_aligned",
                    "actor_pakistan": "transactional",
                    "actor_turkey": "transactional",
                    "actor_egypt": "transactional",
                    "actor_uae": "security_aligned",
                    "actor_kuwait": "security_aligned",
                    "actor_bahrain": "security_aligned",
                },
                "preferred_domain_actions": [
                    "limited retaliation",
                    "air and missile pressure",
                    "maritime protection posture",
                    "backchannel concessions",
                    "allied reassurance",
                ],
            },
        },
        {
            "actor_id": "actor_iran",
            "name": "Iran",
            "role_label": "state_power",
            "role_description": (
                "Principal target of US-Israeli pressure, focused on regime survival, retaliatory credibility, "
                "and preserving leverage through maritime and regional escalation."
            ),
            "base_objectives": [
                "preserve regime continuity",
                "impose costs on US and Israeli operations",
                "retain leverage over the Strait of Hormuz",
                "split the opposing coalition",
            ],
            "base_priorities": {
                "regime_survival": 0.98,
                "deterrent_response": 0.90,
                "maritime_leverage": 0.79,
                "negotiation_space": 0.45,
            },
            "constraints": [
                "risk of severe infrastructure loss",
                "economic pressure",
                "need to preserve domestic legitimacy",
                "risk of over-escalation provoking sustained US expansion",
            ],
            "capabilities": [
                "propose",
                "request",
                "challenge",
                "support",
                "resist",
                "escalate",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "direct regime-collapse campaign",
                "loss of Hormuz leverage",
                "perceived capitulation without reciprocal concessions",
            ],
            "interaction_style": "defensive",
            "metadata": {
                "bloc": "revisionist_state",
                "association_map": {
                    "actor_us": "adversarial",
                    "actor_israel": "adversarial",
                    "actor_saudi": "coercive",
                    "actor_pakistan": "transactional",
                    "actor_turkey": "transactional",
                    "actor_egypt": "transactional",
                    "actor_uae": "coercive",
                    "actor_kuwait": "coercive",
                    "actor_bahrain": "coercive",
                },
                "preferred_domain_actions": [
                    "retaliatory signaling",
                    "proxy pressure",
                    "Hormuz coercion",
                    "conditional diplomacy",
                    "asymmetric escalation",
                ],
            },
        },
        {
            "actor_id": "actor_israel",
            "name": "Israel",
            "role_label": "regional_military_actor",
            "role_description": (
                "Core military participant seeking to sustain pressure on Iranian capabilities "
                "while avoiding coalition slippage or premature de-escalation."
            ),
            "base_objectives": [
                "degrade Iranian military and strategic capabilities",
                "maintain US strategic commitment",
                "prevent a ceasefire that preserves Iranian leverage unchanged",
            ],
            "base_priorities": {
                "military_pressure": 0.94,
                "us_alignment": 0.86,
                "regional_deterrence": 0.80,
                "deescalation": 0.28,
            },
            "constraints": [
                "dependence on US coordination",
                "risk of wider multi-front escalation",
                "domestic pressure over war aims",
            ],
            "capabilities": [
                "propose",
                "request",
                "challenge",
                "support",
                "resist",
                "escalate",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "US pressure for a settlement that leaves Iran strategically stronger",
                "expanded Iranian missile pressure without response",
            ],
            "interaction_style": "assertive",
            "metadata": {
                "bloc": "western_security",
                "association_map": {
                    "actor_us": "aligned",
                    "actor_iran": "adversarial",
                    "actor_saudi": "quiet_convergence",
                    "actor_uae": "quiet_convergence",
                    "actor_bahrain": "quiet_convergence",
                    "actor_turkey": "low_trust",
                    "actor_egypt": "cold_peace",
                    "actor_pakistan": "distant",
                },
                "preferred_domain_actions": [
                    "continued military pressure",
                    "allied signaling",
                    "challenge diplomacy viewed as premature",
                ],
            },
        },
        {
            "actor_id": "actor_saudi",
            "name": "Saudi Arabia",
            "role_label": "exposed_regional_power",
            "role_description": (
                "Key Gulf actor balancing US security alignment, protection of energy infrastructure, "
                "and a strong preference to avoid becoming the main battlefield."
            ),
            "base_objectives": [
                "protect territory and energy infrastructure",
                "avoid direct entry into full-scale war",
                "preserve US security guarantees",
                "support a workable de-escalation track",
            ],
            "base_priorities": {
                "infrastructure_protection": 0.93,
                "deescalation": 0.78,
                "us_alignment": 0.74,
                "regional_leadership": 0.63,
            },
            "constraints": [
                "exposure of bases and infrastructure",
                "oil-market shock sensitivity",
                "need to coordinate across Gulf partners",
            ],
            "capabilities": [
                "propose",
                "request",
                "challenge",
                "support",
                "resist",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "sustained strikes on Saudi territory",
                "collapse of US defensive assurances",
                "being forced into overt direct war leadership",
            ],
            "interaction_style": "guarded",
            "metadata": {
                "bloc": "gulf_security",
                "association_map": {
                    "actor_us": "security_aligned",
                    "actor_iran": "adversarial_but_escalation_averse",
                    "actor_israel": "quiet_convergence",
                    "actor_pakistan": "diplomatic_partner",
                    "actor_turkey": "diplomatic_partner",
                    "actor_egypt": "diplomatic_partner",
                    "actor_uae": "aligned",
                    "actor_kuwait": "aligned",
                    "actor_bahrain": "aligned",
                },
                "preferred_domain_actions": [
                    "request additional protection",
                    "support mediation",
                    "signal restraint",
                    "coordinate Gulf defense",
                ],
            },
        },
        {
            "actor_id": "actor_pakistan",
            "name": "Pakistan",
            "role_label": "mediator_state",
            "role_description": (
                "Primary diplomatic bridge actor trying to keep indirect talks alive while avoiding direct military alignment."
            ),
            "base_objectives": [
                "keep a diplomatic channel open",
                "prevent spillover onto Pakistani interests",
                "retain credibility with both Washington and Tehran",
                "avoid being drawn into direct military alignment",
            ],
            "base_priorities": {
                "mediation": 0.91,
                "regional_stability": 0.82,
                "neutrality": 0.76,
                "prestige": 0.58,
            },
            "constraints": [
                "limited coercive leverage",
                "suspicion from both hardline camps",
                "dependence on other actors accepting mediation",
            ],
            "capabilities": [
                "propose",
                "request",
                "support",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "collapse of all indirect diplomatic channels",
                "major spillover into Pakistan-linked shipping or border security",
            ],
            "interaction_style": "diplomatic",
            "metadata": {
                "bloc": "mediation_track",
                "association_map": {
                    "actor_us": "balancing",
                    "actor_iran": "balancing",
                    "actor_saudi": "balancing",
                    "actor_turkey": "mediator_partner",
                    "actor_egypt": "mediator_partner",
                },
                "preferred_domain_actions": [
                    "host indirect talks",
                    "circulate ceasefire proposals",
                    "sequence confidence-building measures",
                    "reframe public positions into negotiable terms",
                ],
            },
        },
        {
            "actor_id": "actor_turkey",
            "name": "Turkey",
            "role_label": "regional_balancer",
            "role_description": (
                "Regional power seeking to shape the settlement space, avoid a larger war, "
                "and preserve autonomy across rival camps."
            ),
            "base_objectives": [
                "prevent wider regional war",
                "retain influence over any settlement process",
                "preserve strategic autonomy across blocs",
            ],
            "base_priorities": {
                "regional_influence": 0.79,
                "deescalation": 0.74,
                "strategic_autonomy": 0.73,
                "economic_stability": 0.62,
            },
            "constraints": [
                "competing regional commitments",
                "mistrust from multiple sides",
                "need to avoid over-identifying with either camp",
            ],
            "capabilities": [
                "propose",
                "request",
                "challenge",
                "support",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "regional war that collapses all mediation space",
                "loss of Turkish diplomatic relevance",
            ],
            "interaction_style": "opportunistic",
            "metadata": {
                "bloc": "mediation_track",
                "association_map": {
                    "actor_us": "transactional",
                    "actor_iran": "transactional",
                    "actor_pakistan": "mediator_partner",
                    "actor_saudi": "mediator_partner",
                    "actor_egypt": "mediator_partner",
                    "actor_israel": "low_trust",
                },
                "preferred_domain_actions": [
                    "co-sponsor diplomacy",
                    "signal conditional pressure",
                    "broker maritime confidence-building",
                ],
            },
        },
        {
            "actor_id": "actor_egypt",
            "name": "Egypt",
            "role_label": "regional_stability_actor",
            "role_description": (
                "Regional actor prioritizing stability, trade-route normalization, and diplomatic coordination."
            ),
            "base_objectives": [
                "reduce regional instability",
                "support a viable diplomatic coalition",
                "protect trade-route and energy security",
                "maintain regional relevance",
            ],
            "base_priorities": {
                "stability": 0.83,
                "trade_route_security": 0.78,
                "diplomacy": 0.77,
                "prestige": 0.52,
            },
            "constraints": [
                "limited coercive leverage",
                "economic sensitivity to prolonged disruption",
                "need to coordinate with other Arab and mediator states",
            ],
            "capabilities": [
                "propose",
                "request",
                "support",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "extended maritime or energy disruption",
                "complete diplomatic collapse",
            ],
            "interaction_style": "guarded",
            "metadata": {
                "bloc": "mediation_track",
                "association_map": {
                    "actor_us": "transactional",
                    "actor_iran": "escalation_averse",
                    "actor_pakistan": "mediator_partner",
                    "actor_turkey": "mediator_partner",
                    "actor_saudi": "mediator_partner",
                    "actor_israel": "cold_peace",
                },
                "preferred_domain_actions": [
                    "support de-escalation statement",
                    "back channel sequencing",
                    "trade-route stabilization signaling",
                ],
            },
        },
        {
            "actor_id": "actor_uae",
            "name": "United Arab Emirates",
            "role_label": "exposed_gulf_actor",
            "role_description": (
                "Financial and infrastructure-sensitive Gulf actor seeking strong protection without direct war entry."
            ),
            "base_objectives": [
                "protect infrastructure and investor confidence",
                "avoid direct military entry",
                "preserve US defensive cover",
                "restore maritime and commercial normalcy",
            ],
            "base_priorities": {
                "infrastructure_protection": 0.90,
                "financial_stability": 0.88,
                "deescalation": 0.72,
                "us_alignment": 0.71,
            },
            "constraints": [
                "high exposure to strikes and economic confidence shocks",
                "limited appetite for overt direct confrontation",
            ],
            "capabilities": [
                "request",
                "challenge",
                "support",
                "resist",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "repeated direct infrastructure targeting",
                "collapse of maritime security",
            ],
            "interaction_style": "guarded",
            "metadata": {
                "bloc": "gulf_security",
                "association_map": {
                    "actor_us": "security_aligned",
                    "actor_iran": "coercive",
                    "actor_saudi": "aligned",
                    "actor_bahrain": "aligned",
                    "actor_israel": "quiet_convergence",
                },
                "preferred_domain_actions": [
                    "request stronger air and missile defense",
                    "support Gulf coordination",
                    "press for shipping stabilization",
                ],
            },
        },
        {
            "actor_id": "actor_kuwait",
            "name": "Kuwait",
            "role_label": "exposed_gulf_actor",
            "role_description": (
                "US-aligned Gulf state focused on protecting bases, avoiding becoming an escalation platform, and preserving stability."
            ),
            "base_objectives": [
                "protect domestic territory and US-linked facilities",
                "avoid becoming a direct battlefield",
                "support Gulf de-escalation",
            ],
            "base_priorities": {
                "force_protection": 0.87,
                "deescalation": 0.79,
                "gulf_coordination": 0.70,
                "us_alignment": 0.68,
            },
            "constraints": [
                "small-state vulnerability",
                "dependence on larger security partners",
            ],
            "capabilities": [
                "request",
                "support",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "major repeated strikes on bases or radar systems",
                "being forced into overt direct combat leadership",
            ],
            "interaction_style": "cautious",
            "metadata": {
                "bloc": "gulf_security",
                "association_map": {
                    "actor_us": "security_aligned",
                    "actor_iran": "coercive",
                    "actor_saudi": "aligned",
                    "actor_bahrain": "aligned",
                    "actor_uae": "aligned",
                },
                "preferred_domain_actions": [
                    "request defensive reinforcement",
                    "support Gulf bloc statements",
                    "avoid provocative public posturing",
                ],
            },
        },
        {
            "actor_id": "actor_bahrain",
            "name": "Bahrain",
            "role_label": "exposed_gulf_actor",
            "role_description": (
                "Small but symbolically important Gulf actor with close US security ties and high sensitivity to direct targeting."
            ),
            "base_objectives": [
                "protect critical infrastructure",
                "preserve US security ties",
                "avoid additional direct strikes",
                "remain coordinated with Gulf partners",
            ],
            "base_priorities": {
                "infrastructure_protection": 0.90,
                "us_alignment": 0.77,
                "gulf_coordination": 0.75,
                "deescalation": 0.69,
            },
            "constraints": [
                "high vulnerability to coercive signaling",
                "limited independent deterrent capacity",
            ],
            "capabilities": [
                "request",
                "challenge",
                "support",
                "deescalate",
                "withhold",
                "signal",
                "reframe",
            ],
            "red_lines": [
                "repeated attacks on industrial or strategic facilities",
                "visible abandonment by security partners",
            ],
            "interaction_style": "guarded",
            "metadata": {
                "bloc": "gulf_security",
                "association_map": {
                    "actor_us": "security_aligned",
                    "actor_iran": "coercive",
                    "actor_saudi": "aligned",
                    "actor_uae": "aligned",
                    "actor_israel": "quiet_convergence",
                },
                "preferred_domain_actions": [
                    "request stronger defense umbrella",
                    "signal deterrent resolve",
                    "support de-escalation from a security-first position",
                ],
            },
        },
    ]

    actor_ids = [actor["actor_id"] for actor in actors]

    relationships = [
        _rel(
            "actor_us", "actor_iran",
            association="adversarial",
            trust=0.05, alignment=0.02, conflict=0.96, dependency=0.25, influence=0.85, reliability=0.12,
            history="Severe wartime hostility, mutual coercion, and near-zero strategic trust.",
            tags=["war", "deterrence", "escalation"],
        ),
        _rel(
            "actor_iran", "actor_us",
            association="adversarial",
            trust=0.03, alignment=0.01, conflict=0.98, dependency=0.20, influence=0.78, reliability=0.08,
            history="Iran sees the US as the main coercive opponent but still as the central bargaining counterpart.",
            tags=["war", "deterrence", "negotiation"],
        ),
        _rel(
            "actor_us", "actor_israel",
            association="aligned",
            trust=0.88, alignment=0.92, conflict=0.05, dependency=0.45, influence=0.86, reliability=0.83,
            history="Strong wartime alignment, though Washington wants escalation control.",
            tags=["alliance", "wartime_coordination"],
        ),
        _rel(
            "actor_israel", "actor_us",
            association="aligned",
            trust=0.84, alignment=0.90, conflict=0.10, dependency=0.72, influence=0.68, reliability=0.80,
            history="Israel relies on US backing but worries about premature diplomatic restraint.",
            tags=["alliance", "wartime_coordination"],
        ),
        _rel(
            "actor_us", "actor_saudi",
            association="security_aligned",
            trust=0.75, alignment=0.78, conflict=0.18, dependency=0.62, influence=0.82, reliability=0.72,
            history="Security coordination remains strong, but both sides are sensitive to direct strikes on Saudi soil.",
            tags=["base_security", "gulf"],
        ),
        _rel(
            "actor_saudi", "actor_us",
            association="security_aligned",
            trust=0.71, alignment=0.74, conflict=0.18, dependency=0.84, influence=0.59, reliability=0.69,
            history="Saudi Arabia needs visible US protection but wants Washington to avoid uncontrolled expansion.",
            tags=["base_security", "gulf"],
        ),
        _rel(
            "actor_us", "actor_pakistan",
            association="transactional",
            trust=0.54, alignment=0.45, conflict=0.22, dependency=0.31, influence=0.55, reliability=0.52,
            history="Useful diplomatic channel but limited confidence in how far Islamabad can move Tehran.",
            tags=["mediation", "transactional"],
        ),
        _rel(
            "actor_pakistan", "actor_us",
            association="balancing",
            trust=0.49, alignment=0.42, conflict=0.24, dependency=0.37, influence=0.46, reliability=0.50,
            history="Pakistan sees the US as necessary for any settlement but not fully trusted.",
            tags=["mediation", "balancing"],
        ),
        _rel(
            "actor_us", "actor_turkey",
            association="transactional",
            trust=0.48, alignment=0.41, conflict=0.29, dependency=0.38, influence=0.57, reliability=0.47,
            history="Mutual utility exists, but alignment is partial and tactical.",
            tags=["mediation", "regional_balance"],
        ),
        _rel(
            "actor_turkey", "actor_us",
            association="transactional",
            trust=0.43, alignment=0.39, conflict=0.31, dependency=0.33, influence=0.52, reliability=0.46,
            history="Turkey values leverage with Washington but resists appearing subordinate.",
            tags=["mediation", "regional_balance"],
        ),
        _rel(
            "actor_us", "actor_egypt",
            association="transactional",
            trust=0.58, alignment=0.56, conflict=0.18, dependency=0.29, influence=0.52, reliability=0.60,
            history="Egypt is seen as a steady but limited diplomatic and regional-stability partner.",
            tags=["mediation", "stability"],
        ),
        _rel(
            "actor_egypt", "actor_us",
            association="transactional",
            trust=0.55, alignment=0.53, conflict=0.19, dependency=0.41, influence=0.38, reliability=0.57,
            history="Egypt values US coordination but prefers a stabilizing role over military alignment.",
            tags=["mediation", "stability"],
        ),
        _rel(
            "actor_us", "actor_uae",
            association="security_aligned",
            trust=0.74, alignment=0.76, conflict=0.16, dependency=0.59, influence=0.74, reliability=0.70,
            history="High-value security partnership under strain from infrastructure-risk exposure.",
            tags=["gulf", "infrastructure_risk"],
        ),
        _rel(
            "actor_uae", "actor_us",
            association="security_aligned",
            trust=0.72, alignment=0.74, conflict=0.14, dependency=0.79, influence=0.45, reliability=0.68,
            history="The UAE needs reassurance but wants rapid stabilization of the commercial environment.",
            tags=["gulf", "infrastructure_risk"],
        ),
        _rel(
            "actor_us", "actor_kuwait",
            association="security_aligned",
            trust=0.73, alignment=0.75, conflict=0.15, dependency=0.61, influence=0.72, reliability=0.70,
            history="Security ties are solid, shaped by base vulnerability and defensive dependence.",
            tags=["gulf", "base_security"],
        ),
        _rel(
            "actor_kuwait", "actor_us",
            association="security_aligned",
            trust=0.70, alignment=0.72, conflict=0.15, dependency=0.82, influence=0.38, reliability=0.67,
            history="Kuwait strongly values US protection while preferring not to become a high-visibility launchpad.",
            tags=["gulf", "base_security"],
        ),
        _rel(
            "actor_us", "actor_bahrain",
            association="security_aligned",
            trust=0.75, alignment=0.78, conflict=0.13, dependency=0.64, influence=0.73, reliability=0.71,
            history="Bahrain is a sensitive but closely aligned security partner with symbolic and strategic weight.",
            tags=["gulf", "critical_infrastructure"],
        ),
        _rel(
            "actor_bahrain", "actor_us",
            association="security_aligned",
            trust=0.73, alignment=0.76, conflict=0.13, dependency=0.84, influence=0.36, reliability=0.69,
            history="Bahrain needs visible US commitment after direct pressure on Gulf-linked assets.",
            tags=["gulf", "critical_infrastructure"],
        ),
        _rel(
            "actor_iran", "actor_israel",
            association="adversarial",
            trust=0.01, alignment=0.01, conflict=0.99, dependency=0.12, influence=0.76, reliability=0.06,
            history="Maximum conflict relationship with no real trust and high retaliatory intensity.",
            tags=["war", "retaliation"],
        ),
        _rel(
            "actor_israel", "actor_iran",
            association="adversarial",
            trust=0.02, alignment=0.01, conflict=0.99, dependency=0.18, influence=0.81, reliability=0.09,
            history="Israel views Iran as the central strategic threat and opposes a freeze that preserves Iranian leverage.",
            tags=["war", "retaliation"],
        ),
        _rel(
            "actor_iran", "actor_saudi",
            association="coercive",
            trust=0.12, alignment=0.11, conflict=0.84, dependency=0.19, influence=0.54, reliability=0.25,
            history="High mutual suspicion shaped by strikes, base exposure, and regional rivalry.",
            tags=["gulf", "coercion"],
        ),
        _rel(
            "actor_saudi", "actor_iran",
            association="adversarial_but_escalation_averse",
            trust=0.16, alignment=0.14, conflict=0.79, dependency=0.23, influence=0.47, reliability=0.28,
            history="Saudi Arabia sees Iran as the proximate coercive threat but still wants a managed off-ramp.",
            tags=["gulf", "coercion", "deescalation_interest"],
        ),
        _rel(
            "actor_iran", "actor_pakistan",
            association="transactional",
            trust=0.42, alignment=0.37, conflict=0.26, dependency=0.28, influence=0.41, reliability=0.46,
            history="Pakistan is a useful diplomatic bridge but not a fully trusted strategic partner.",
            tags=["mediation"],
        ),
        _rel(
            "actor_pakistan", "actor_iran",
            association="balancing",
            trust=0.47, alignment=0.40, conflict=0.24, dependency=0.33, influence=0.39, reliability=0.48,
            history="Pakistan has enough access to matter diplomatically but limited power to compel Tehran.",
            tags=["mediation"],
        ),
        _rel(
            "actor_iran", "actor_turkey",
            association="transactional",
            trust=0.39, alignment=0.35, conflict=0.30, dependency=0.27, influence=0.43, reliability=0.44,
            history="Useful regional channel with mixed strategic trust.",
            tags=["mediation", "regional_balance"],
        ),
        _rel(
            "actor_turkey", "actor_iran",
            association="transactional",
            trust=0.41, alignment=0.36, conflict=0.28, dependency=0.29, influence=0.42, reliability=0.45,
            history="Turkey wants leverage with Iran without being absorbed into Tehran's posture.",
            tags=["mediation", "regional_balance"],
        ),
        _rel(
            "actor_iran", "actor_egypt",
            association="transactional",
            trust=0.34, alignment=0.29, conflict=0.33, dependency=0.20, influence=0.35, reliability=0.39,
            history="Low warmth but a potentially useful diplomatic channel in a wider Arab mediation package.",
            tags=["mediation"],
        ),
        _rel(
            "actor_egypt", "actor_iran",
            association="escalation_averse",
            trust=0.36, alignment=0.31, conflict=0.30, dependency=0.23, influence=0.31, reliability=0.42,
            history="Egypt wants to avoid wider escalation and preserve room for indirect bargaining.",
            tags=["mediation"],
        ),
        _rel(
            "actor_iran", "actor_uae",
            association="coercive",
            trust=0.11, alignment=0.10, conflict=0.83, dependency=0.21, influence=0.53, reliability=0.24,
            history="Iran sees the UAE as vulnerable to coercive signaling tied to US-linked regional posture.",
            tags=["gulf", "infrastructure_risk"],
        ),
        _rel(
            "actor_uae", "actor_iran",
            association="coercive",
            trust=0.14, alignment=0.12, conflict=0.78, dependency=0.24, influence=0.37, reliability=0.29,
            history="The UAE views Iran as the main immediate risk to infrastructure and commercial stability.",
            tags=["gulf", "infrastructure_risk"],
        ),
        _rel(
            "actor_iran", "actor_kuwait",
            association="coercive",
            trust=0.10, alignment=0.10, conflict=0.81, dependency=0.19, influence=0.49, reliability=0.23,
            history="Iran sees Kuwait as part of the exposed Gulf security layer around US force posture.",
            tags=["gulf", "base_security"],
        ),
        _rel(
            "actor_kuwait", "actor_iran",
            association="coercive",
            trust=0.13, alignment=0.11, conflict=0.75, dependency=0.28, influence=0.29, reliability=0.28,
            history="Kuwait fears further pressure but prefers quiet de-escalation over public confrontation.",
            tags=["gulf", "base_security"],
        ),
        _rel(
            "actor_iran", "actor_bahrain",
            association="coercive",
            trust=0.08, alignment=0.07, conflict=0.87, dependency=0.18, influence=0.57, reliability=0.20,
            history="Bahrain is viewed in Tehran as a vulnerable pressure point tied to the US-led security architecture.",
            tags=["gulf", "critical_infrastructure"],
        ),
        _rel(
            "actor_bahrain", "actor_iran",
            association="coercive",
            trust=0.09, alignment=0.08, conflict=0.82, dependency=0.22, influence=0.26, reliability=0.23,
            history="Bahrain sees Iran as a direct coercive threat after pressure on Gulf-linked assets.",
            tags=["gulf", "critical_infrastructure"],
        ),
        _rel(
            "actor_israel", "actor_saudi",
            association="quiet_convergence",
            trust=0.36, alignment=0.48, conflict=0.34, dependency=0.11, influence=0.32, reliability=0.41,
            history="Convergence against Iran exists, but formal trust remains limited and escalation preferences differ.",
            tags=["quiet_alignment", "iran"],
        ),
        _rel(
            "actor_saudi", "actor_israel",
            association="quiet_convergence",
            trust=0.31, alignment=0.44, conflict=0.38, dependency=0.10, influence=0.28, reliability=0.39,
            history="Saudi Arabia shares threat concerns about Iran but is wary of Israeli moves widening the war.",
            tags=["quiet_alignment", "iran"],
        ),
        _rel(
            "actor_israel", "actor_uae",
            association="quiet_convergence",
            trust=0.42, alignment=0.56, conflict=0.27, dependency=0.10, influence=0.29, reliability=0.47,
            history="Indirect convergence exists, especially around threat perceptions, but the UAE prioritizes stability.",
            tags=["quiet_alignment", "iran"],
        ),
        _rel(
            "actor_uae", "actor_israel",
            association="quiet_convergence",
            trust=0.39, alignment=0.53, conflict=0.29, dependency=0.09, influence=0.24, reliability=0.45,
            history="The UAE wants Iranian pressure contained but avoids identification with maximalist war aims.",
            tags=["quiet_alignment", "iran"],
        ),
        _rel(
            "actor_israel", "actor_bahrain",
            association="quiet_convergence",
            trust=0.41, alignment=0.55, conflict=0.26, dependency=0.08, influence=0.27, reliability=0.46,
            history="Shared threat perception exists, but Bahrain is far more escalation-averse.",
            tags=["quiet_alignment", "iran"],
        ),
        _rel(
            "actor_bahrain", "actor_israel",
            association="quiet_convergence",
            trust=0.37, alignment=0.51, conflict=0.29, dependency=0.08, influence=0.21, reliability=0.43,
            history="Bahrain accepts quiet convergence but wants the conflict tightly contained.",
            tags=["quiet_alignment", "iran"],
        ),
        _rel(
            "actor_israel", "actor_egypt",
            association="cold_peace",
            trust=0.28, alignment=0.31, conflict=0.41, dependency=0.09, influence=0.24, reliability=0.34,
            history="Functional but low-trust relationship under severe regional stress.",
            tags=["cold_peace"],
        ),
        _rel(
            "actor_egypt", "actor_israel",
            association="cold_peace",
            trust=0.26, alignment=0.28, conflict=0.42, dependency=0.10, influence=0.18, reliability=0.33,
            history="Egypt prefers containment and rejects actions that widen regional instability.",
            tags=["cold_peace"],
        ),
        _rel(
            "actor_israel", "actor_turkey",
            association="low_trust",
            trust=0.21, alignment=0.19, conflict=0.49, dependency=0.08, influence=0.22, reliability=0.31,
            history="Low trust and clashing regional narratives limit cooperative space.",
            tags=["regional_balance"],
        ),
        _rel(
            "actor_turkey", "actor_israel",
            association="low_trust",
            trust=0.19, alignment=0.18, conflict=0.50, dependency=0.07, influence=0.16, reliability=0.30,
            history="Turkey is skeptical of Israeli war aims and sees them as destabilizing the mediation track.",
            tags=["regional_balance"],
        ),
        _rel(
            "actor_saudi", "actor_pakistan",
            association="diplomatic_partner",
            trust=0.66, alignment=0.61, conflict=0.16, dependency=0.39, influence=0.47, reliability=0.63,
            history="Saudi Arabia views Pakistan as a credible diplomatic partner and useful intermediary.",
            tags=["mediation", "gulf"],
        ),
        _rel(
            "actor_pakistan", "actor_saudi",
            association="balancing",
            trust=0.63, alignment=0.58, conflict=0.17, dependency=0.44, influence=0.42, reliability=0.61,
            history="Pakistan coordinates closely with Saudi Arabia but wants to preserve mediator neutrality.",
            tags=["mediation", "gulf"],
        ),
        _rel(
            "actor_saudi", "actor_turkey",
            association="diplomatic_partner",
            trust=0.57, alignment=0.54, conflict=0.23, dependency=0.26, influence=0.36, reliability=0.55,
            history="Shared interest in de-escalation exists despite broader regional differences.",
            tags=["mediation"],
        ),
        _rel(
            "actor_turkey", "actor_saudi",
            association="diplomatic_partner",
            trust=0.55, alignment=0.51, conflict=0.24, dependency=0.25, influence=0.34, reliability=0.53,
            history="Turkey sees Saudi Arabia as necessary to any durable Gulf-facing de-escalation framework.",
            tags=["mediation"],
        ),
        _rel(
            "actor_saudi", "actor_egypt",
            association="diplomatic_partner",
            trust=0.68, alignment=0.66, conflict=0.14, dependency=0.31, influence=0.41, reliability=0.65,
            history="Saudi Arabia and Egypt align strongly on stabilizing the region and avoiding energy shocks.",
            tags=["mediation"],
        ),
        _rel(
            "actor_egypt", "actor_saudi",
            association="diplomatic_partner",
            trust=0.65, alignment=0.63, conflict=0.15, dependency=0.36, influence=0.35, reliability=0.63,
            history="Egypt sees Saudi Arabia as central to any credible Arab de-escalation package.",
            tags=["mediation"],
        ),
        _rel(
            "actor_saudi", "actor_uae",
            association="aligned",
            trust=0.79, alignment=0.81, conflict=0.08, dependency=0.44, influence=0.52, reliability=0.76,
            history="Strong Gulf coordination around defense, energy, and containment of spillover.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_uae", "actor_saudi",
            association="aligned",
            trust=0.78, alignment=0.80, conflict=0.08, dependency=0.42, influence=0.49, reliability=0.75,
            history="The UAE sees Saudi Arabia as the key Gulf anchor for coordinated crisis management.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_saudi", "actor_kuwait",
            association="aligned",
            trust=0.77, alignment=0.79, conflict=0.09, dependency=0.41, influence=0.48, reliability=0.74,
            history="High Gulf security alignment and shared desire to contain spillover.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_kuwait", "actor_saudi",
            association="aligned",
            trust=0.75, alignment=0.77, conflict=0.09, dependency=0.45, influence=0.36, reliability=0.72,
            history="Kuwait leans on Saudi coordination while remaining highly escalation-averse.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_saudi", "actor_bahrain",
            association="aligned",
            trust=0.82, alignment=0.84, conflict=0.07, dependency=0.46, influence=0.54, reliability=0.78,
            history="Very strong Gulf alignment, especially under direct security pressure.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_bahrain", "actor_saudi",
            association="aligned",
            trust=0.80, alignment=0.82, conflict=0.07, dependency=0.51, influence=0.38, reliability=0.76,
            history="Bahrain depends heavily on Saudi political and security coordination.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_pakistan", "actor_turkey",
            association="mediator_partner",
            trust=0.71, alignment=0.69, conflict=0.11, dependency=0.28, influence=0.42, reliability=0.68,
            history="Both are core members of the active diplomatic track.",
            tags=["mediation_track"],
        ),
        _rel(
            "actor_turkey", "actor_pakistan",
            association="mediator_partner",
            trust=0.69, alignment=0.67, conflict=0.12, dependency=0.26, influence=0.39, reliability=0.66,
            history="Turkey sees Pakistan as a crucial channel with both Gulf states and Iran.",
            tags=["mediation_track"],
        ),
        _rel(
            "actor_pakistan", "actor_egypt",
            association="mediator_partner",
            trust=0.64, alignment=0.63, conflict=0.12, dependency=0.24, influence=0.33, reliability=0.62,
            history="Egypt adds Arab legitimacy to the Pakistani mediation track.",
            tags=["mediation_track"],
        ),
        _rel(
            "actor_egypt", "actor_pakistan",
            association="mediator_partner",
            trust=0.62, alignment=0.61, conflict=0.13, dependency=0.22, influence=0.29, reliability=0.61,
            history="Egypt views Pakistan as the convening center for indirect diplomacy.",
            tags=["mediation_track"],
        ),
        _rel(
            "actor_turkey", "actor_egypt",
            association="mediator_partner",
            trust=0.66, alignment=0.62, conflict=0.16, dependency=0.24, influence=0.37, reliability=0.63,
            history="Both actors support diplomacy, though not always with identical regional priorities.",
            tags=["mediation_track"],
        ),
        _rel(
            "actor_egypt", "actor_turkey",
            association="mediator_partner",
            trust=0.64, alignment=0.60, conflict=0.17, dependency=0.23, influence=0.34, reliability=0.61,
            history="Functional alignment within the mediation bloc, despite some strategic distance.",
            tags=["mediation_track"],
        ),
        _rel(
            "actor_uae", "actor_bahrain",
            association="aligned",
            trust=0.73, alignment=0.76, conflict=0.08, dependency=0.27, influence=0.35, reliability=0.71,
            history="Shared Gulf security posture and high concern about infrastructure targeting.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_bahrain", "actor_uae",
            association="aligned",
            trust=0.71, alignment=0.74, conflict=0.09, dependency=0.25, influence=0.31, reliability=0.69,
            history="Bahrain and the UAE stay closely aligned on deterrence and stabilization messaging.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_uae", "actor_kuwait",
            association="aligned",
            trust=0.68, alignment=0.71, conflict=0.09, dependency=0.26, influence=0.31, reliability=0.67,
            history="Moderately strong Gulf coordination with similar exposure concerns.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_kuwait", "actor_uae",
            association="aligned",
            trust=0.66, alignment=0.69, conflict=0.09, dependency=0.24, influence=0.28, reliability=0.66,
            history="Kuwait and the UAE coordinate around defensive and commercial stabilization issues.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_kuwait", "actor_bahrain",
            association="aligned",
            trust=0.62, alignment=0.66, conflict=0.10, dependency=0.22, influence=0.24, reliability=0.63,
            history="Smaller Gulf actors share strong incentives to avoid direct battlefield status.",
            tags=["gulf_coordination"],
        ),
        _rel(
            "actor_bahrain", "actor_kuwait",
            association="aligned",
            trust=0.63, alignment=0.67, conflict=0.10, dependency=0.21, influence=0.24, reliability=0.64,
            history="Both prioritize coalition reassurance and defensive containment.",
            tags=["gulf_coordination"],
        ),
    ]

    environment = {
        "environment_id": "env_us_iran_regional_crisis_20260329",
        "environment_type": "geopolitical_conflict",
        "description": (
            "Regionalized interstate war environment shaped by military retaliation, Gulf-base vulnerability, "
            "shipping disruption, and an active but fragile diplomatic track."
        ),
        "actors": actor_ids,
        "rules": [
            "Actors avoid direct acknowledgment of sensitive quiet alignments unless pressured.",
            "Military and diplomatic signaling can occur simultaneously.",
            "Gulf actors strongly prefer not to become primary battlefields.",
            "Mediator states seek indirect contact and sequencing rather than maximal public commitments.",
        ],
        "norms": [
            "Public messaging often diverges from private bargaining positions.",
            "Threats and reassurance are both used to shape coalition behavior.",
            "Maritime and energy disruption changes actor urgency quickly.",
        ],
        "resources": [
            "military deterrence",
            "air and missile defense coverage",
            "maritime access and shipping lanes",
            "oil market leverage",
            "diplomatic legitimacy",
            "coalition cohesion",
            "public credibility",
        ],
        "deadlines": [
            "Immediate decisions needed after fresh pressure on Gulf-linked targets and military assets.",
            "Diplomatic opening in Islamabad is time-sensitive and may close if retaliation widens.",
        ],
        "external_pressures": [
            "risk of Hormuz disruption",
            "oil-market volatility",
            "pressure on Gulf infrastructure",
            "proxy spillover across the region",
            "domestic political pressure in wartime capitals",
        ],
        "active_issues": [
            "US retaliation scope",
            "Iranian coercive signaling",
            "Israeli pressure for sustained military momentum",
            "Gulf-state force protection",
            "Islamabad mediation track credibility",
            "shipping and energy stabilization",
        ],
        "metadata": {
            "date_anchor": "2026-03-29",
            "country_actors_only": True,
            "proxy_factors_modeled_as_external_pressure": [
                "Houthis",
                "other Iran-aligned proxy actions",
            ],
            "scenario_action_catalog": {
                "coercive": [
                    "limited retaliatory strike",
                    "missile or drone signaling",
                    "base reinforcement",
                    "maritime interdiction posture",
                    "proxy activation signal",
                ],
                "diplomatic": [
                    "host indirect talks",
                    "propose ceasefire sequencing",
                    "seek security guarantees",
                    "issue joint de-escalation statement",
                    "reject proposal and counterframe",
                ],
                "economic_maritime": [
                    "pressure over Hormuz access",
                    "coordinate tanker protection",
                    "harden infrastructure",
                    "signal energy-market stabilization",
                ],
                "information_political": [
                    "public ultimatum",
                    "domestic reassurance speech",
                    "blame attribution",
                    "restraint signaling",
                    "allied burden-sharing request",
                ],
            },
        },
    }

    scenario = {
        "scenario_id": "scenario_hormuz_brinkmanship_after_prince_sultan_strike",
        "title": "Hormuz Brinkmanship After the Prince Sultan Strike",
        "trigger": (
            "Fresh Iranian pressure on Gulf-linked military and industrial targets raises demands for US retaliation "
            "while Pakistan hosts a regional diplomatic track with Saudi Arabia, Turkey, and Egypt."
        ),
        "context_summary": (
            "The United States, Iran, and Israel are at the center of a widening regional conflict. "
            "Gulf states want stronger protection but prefer de-escalation, while Pakistan, Turkey, and Egypt "
            "are trying to convert a narrow diplomatic opening into indirect talks before maritime and infrastructure pressure worsens."
        ),
        "stakeholders": actor_ids,
        "issue_map": [
            "retaliation scope versus restraint",
            "Hormuz leverage and maritime access",
            "Gulf infrastructure and base security",
            "coalition cohesion under asymmetric risk",
            "credibility of indirect diplomacy",
        ],
        "known_facts": [
            "The conflict has widened beyond a bilateral US-Iran confrontation.",
            "Pakistan is hosting a regional diplomatic track with Saudi Arabia, Turkey, and Egypt.",
            "Gulf actors face direct or indirect exposure to strikes and economic disruption.",
            "The Strait of Hormuz is central to coercive leverage and market stability.",
        ],
        "uncertainties": [
            "Whether Washington prioritizes immediate retaliation or sequencing through diplomacy.",
            "Whether Tehran prefers calibrated coercion or broader escalation.",
            "Whether Israel accepts a slower diplomatic track.",
            "Whether Gulf states stay aligned if new strikes continue.",
        ],
        "success_conditions": [
            "No additional Gulf state is drawn into direct combat leadership.",
            "A live indirect diplomatic channel between the US and Iran is sustained.",
            "Shipping pressure eases without either core belligerent claiming total capitulation.",
            "Coalition cohesion survives despite divergent escalation preferences.",
        ],
        "failure_conditions": [
            "Major new strikes on Gulf infrastructure or US forces trigger a harder regional military phase.",
            "Hormuz disruption intensifies and diplomacy collapses.",
            "Mediator states lose credibility and coalition preferences fragment.",
            "One or more exposed Gulf states shift from host/support role into direct wartime participation.",
        ],
        "current_round": 0,
        "status": "active",
        "metadata": {
            "scenario_basis": "news_grounded_template",
            "recommended_round_themes": {
                "1": "shock absorption and coalition signaling",
                "2": "maritime and infrastructure pressure",
                "3": "diplomatic sequencing versus retaliatory escalation",
                "4": "fragile off-ramp or regional widening",
            },
        },
    }

    return {
        "environment": environment,
        "scenario": scenario,
        "actors": actors,
        "relationships": relationships,
    }


build_input = build_us_iran_regional_crisis_input